import = [
	# uncomment the flavour you want below:
	# "~/.config/alacritty/catppuccin-latte.toml"
	# "~/.config/alacritty/catppuccin-frappe.toml"
	# "~/.config/alacritty/catppuccin-macchiato.toml"
	"~/.config/alacritty/catppuccin-mocha.toml",
]

[window]
decorations = "buttonless"
padding = { x = 20, y = 12 }
opacity = 0.8
blur = false

[font]
size = 13
normal = { family = "JetBrainsMono Nerd Font" }

[mouse]
hide_when_typing = true
