# # Shell variables
# # Generated by 'wal'
# wallpaper="/Users/adjaythakoerdien/Pictures/wallpapers/wp13498619-4k-anime-room-wallpapers.png"
#
# # Special
# background='#100912'
# foreground='#adc5d8'
# cursor='#adc5d8'
#
# # Colors
# color0='#100912'
# color1='#9A235E'
# color2='#CF4466'
# color3='#36559D'
# color4='#61549C'
# color5='#9E5699'
# color6='#CD5B99'
# color7='#adc5d8'
# color8='#798997'
# color9='#9A235E'
# color10='#CF4466'
# color11='#36559D'
# color12='#61549C'
# color13='#9E5699'
# color14='#CD5B99'
# color15='#adc5d8'
#
# # FZF colors
# export FZF_DEFAULT_OPTS="
#     $FZF_DEFAULT_OPTS
#     --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
#     --color info:7,prompt:2,spinner:1,pointer:232,marker:1
# "
#
# # Fix LS_COLORS being unreadable.
# export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
#
