# Auto genereted theme by Jay from pywal for Ghostty

palette = 0=#030F0C
palette = 1=#0C7347
palette = 2=#236B4A
palette = 3=#658B3F
palette = 4=#0B8D52
palette = 5=#10A964
palette = 6=#09C66D
palette = 7=#cbcd9d
palette = 8=#8e8f6d
palette = 9=#0C7347
palette = 10=#236B4A
palette = 11=#658B3F
palette = 12=#0B8D52
palette = 13=#10A964
palette = 14=#09C66D
palette = 15=#cbcd9d

background = #030F0C
foreground = #cbcd9d
cursor-color = #cbcd9d

selection-background = #8e8f6d
selection-foreground = #cbcd9d
