# Auto genereted theme by Jay from pywal for Ghostty

palette = 0=#080B0D
palette = 1=#009745
palette = 2=#27aa00
palette = 3=#009c5a
palette = 4=#00b360
palette = 5=#00b867
palette = 6=#00f629
palette = 7=#bedeb1
palette = 8=#859b7b
palette = 9=#009745
palette = 10=#27aa00
palette = 11=#009c5a
palette = 12=#00b360
palette = 13=#00b867
palette = 14=#00f629
palette = 15=#bedeb1

background = #080B0D
foreground = #bedeb1
cursor-color = #bedeb1

selection-background = #859b7b
selection-foreground = #bedeb1
